export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const START_FETCH_MESSAGE = "START_FETCH_MESSAGE";
export const END_FETCH_MESSAGE = "END_FETCH_MESSAGE";

